# kubectl create service clusterip web-app --tcp=80:80 -n ej2 --dry-run=client -o  yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-app
  name: web-app
  namespace: ej2
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web-app
  type: ClusterIP
status:
  loadBalancer: {}