apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: ej4
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

--- 

# kubectl create deployment  --image=postgres:15 --port=5432 -n ej4 --dry-run=client -o yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres-deployment
  name: postgres-deployment
  namespace: ej4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: postgres-deployment
    spec:
      containers:
      - image: postgres:15
        name: postgres
        ports:
        - containerPort: 5432
        resources: {}
        env:
        - name: POSTGRES_PASSWORD
          value: "secreto123"
        - name: POSTGRES_DB
          value: "testdb"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc # El nombre del PVC de arriba
        
status: {}

--- 

# kubectl create service clusterip postgres-service -n ej4 --tcp=5432:5432 --dry-run=client -o yaml 
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-service
  name: postgres-service
  namespace: ej4
spec:
  ports:
  - name: 5432-5432
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres-deployment # Cambiamos a donde apunta
  type: ClusterIP
status:
  loadBalancer: {}